/*Here, movies materialized views table has been created that will contain the pivoted values from movies table.
This table can be refreshed as and when the movies table is updated. This can be configoured as per the requirements with the help of triggers.
For now, this table will never be refreshed unless done manually.*/

CREATE TABLE netflix_analysis.`movies _mv` (
  `index` bigint(20) DEFAULT NULL,
  `title` text,
  `year` text,
  `duration` text,
  `votes` double DEFAULT NULL,
  `reviews_from_users` double DEFAULT NULL,
  `reviews_from_critics` double DEFAULT NULL,
  `allgenders_18age_avg_vote` double DEFAULT NULL,
  `allgenders_18age_votes` double DEFAULT NULL,
  `allgenders_30age_avg_vote` double DEFAULT NULL,
  `allgenders_30age_votes` double DEFAULT NULL,
  `allgenders_45age_avg_vote` double DEFAULT NULL,
  `allgenders_45age_votes` double DEFAULT NULL,
  `males_allages_avg_vote` double DEFAULT NULL,
  `males_allages_votes` double DEFAULT NULL,
  `males_18age_avg_vote` double DEFAULT NULL,
  `males_18age_votes` double DEFAULT NULL,
  `males_30age_avg_vote` double DEFAULT NULL,
  `males_30age_votes` double DEFAULT NULL,
  `males_45age_avg_vote` double DEFAULT NULL,
  `males_45age_votes` double DEFAULT NULL,
  `females_allages_avg_vote` double DEFAULT NULL,
  `females_allages_votes` double DEFAULT NULL,
  `females_18age_avg_vote` double DEFAULT NULL,
  `females_18age_votes` double DEFAULT NULL,
  `females_30age_avg_vote` double DEFAULT NULL,
  `females_30age_votes` double DEFAULT NULL,
  `females_45age_avg_vote` double DEFAULT NULL,
  `females_45age_votes` double DEFAULT NULL,
  `top1000_voters_rating` double DEFAULT NULL,
  `top1000_voters_votes` double DEFAULT NULL,
  `us_voters_rating` double DEFAULT NULL,
  `us_voters_votes` double DEFAULT NULL,
  `non_us_voters_rating` double DEFAULT NULL,
  `non_us_voters_votes` double DEFAULT NULL,
  `total_countries` double DEFAULT NULL,
  `total_languages` double DEFAULT NULL,
  `total_actors` double DEFAULT NULL,
  `content_rating` text,
  `published_year` text,
  `tomatometer_score` double DEFAULT NULL,
  `audience_score` double DEFAULT NULL,
  `tomatometer_counts` double DEFAULT NULL,
  `audience_counts` double DEFAULT NULL,
  `tomatometer_status` text,
  `audience_status` text,
  `tomatometer_top_critics_count` double DEFAULT NULL,
  `tomatometer_fresh_critics_count` double DEFAULT NULL,
  `tomatometer_rotten_critics_count` double DEFAULT NULL,
  `streaming_year` text,
  `production_company` text,
  `ratings` double DEFAULT NULL,
  `genre_pivot` text,
  `genre` text,
  `country_pivot` text,
  `country` text,
  `language_pivot` text,
  `language` text,
  `actors_pivot` text,
  `actor` text,
  `writers_pivot` text,
  `writer` text,
  `director_pivot` text,
  `director` text
)
